# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            LINDA+
tagline:          'A Jekyll theme'
description:      'Linear Integer programming for Network reconstruction using transcriptomics and Differential splicing data Analysis'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Enio Gjerga'
  url:            https://enio23.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dieterich-lab/LINDAPlus
